### PR TITLE
Use Truth for assertions

### PR DESCRIPTION
**Pull request by electrum**

### CODE REVIEW

**Comment by martint** [comment]
Why Truth instead of AssertJ? I looked at this a while ago and concluded AssertJ was preferable, but don't know the current state of things.

**Comment by electrum** [comment]
It's hard to find a good comparison. This is the best I could find:

https://github.com/google/truth/issues/306

Looking over AssertJ again, I think it has more features like combination, transform, etc. I'll do a version with that and see how it looks.

**Comment by electrum** [comment]
I had high hopes for Truth given it's from the Guava team, but this needs more exploration.

**Comment by electrum** [comment]
AssertJ version: https://github.com/airlift/units/pull/4

This project is tiny, but even so, AssertJ was better than Truth in two areas:
* Allows specifying percentages for fuzzy comparisons.
* Less boilerplate around creating a custom assertion. Instead of needing to create an assertion factory class in the fluent entry point `assertThat()`, simply new up the assertion class directly. `ConstraintValidator` might be pathological due to the heavy generics involved, but it made the Truth version quite annoying.

One interesting difference is in how you fail in a custom assertion. With Truth, it constructs the full method for you, whereas in AssertJ you do that yourself:
```java
// Truth
fail("is valid for", value);

// AssertJ
failWithMessage("Expected <%s> to be valid for <%s>", actual, value);
```
The Truth way seems nicer but is less flexible (unclear if that matters in practice).

**Comment by electrum** [comment]
I previously tried converting Airlift `Assertions` to Truth and gave up because it was lacking equivalent functionality. So far, everything is a one line replacement in AssertJ.

**Pull request closed without merging**
